player removeItems "ACE_adenosine";
player removeItems "ACE_bloodIV";
player removeItems "ACE_bloodIV_250";
player removeItems "ACE_bloodIV_500";
player removeItems "ACE_plasmaIV";
player removeItems "ACE_plasmaIV_250";
player removeItems "ACE_plasmaIV_500";
player removeItems "ACE_surgicalKit";
player removeItems "adv_aceCPR_AED";
player removeItems "adv_aceSplint_splint";
player removeItems "ACE_salineIV";
player removeItems "ACE_salineIV_250";
player removeItems "ACE_salineIV_500";
player removeItems "ACE_personalAidKit";
player removeItems "ACE_epinephrine";
player removeItems "ACE_morphine";
player removeItems "ACE_quikclot";
player removeItems "ACE_packingBandage";
player removeItems "ACE_elasticBandage";
player removeItems "ACE_tourniquet";
player removeItems "ACE_atropine";
for "_i" from 1 to 5 do {player addItem "ACE_epinephrine";};
for "_i" from 1 to 5 do {player addItem "ACE_morphine";};
for "_i" from 1 to 4 do {player addItem "ACE_tourniquet";};
for "_i" from 1 to 15 do {player addItem "ACE_elasticBandage";};
for "_i" from 1 to 15 do {player addItem "ACE_packingBandage";};
for "_i" from 1 to 15 do {player addItem "ACE_fieldDressing";};
for "_i" from 1 to 3 do {player addItem "ACE_salineIV_250";};
for "_i" from 1 to 4 do {player addItem "ACE_splint";};